name = "ai-overview-worker"
main = "src/index.js"
compatibility_date = "2025-06-11"

[site]
bucket = "src/public"  

[build.upload]
format = "modules"

[durable_objects]
bindings = []

[wasm_modules]
bindings = []

[bindings]
type = "static_asset"
name = "ASSETS"


[vars] 
ENVIRONMENT = "default"
LOG_LEVEL = "debug" 
MAX_DOCS = "12"

[env.preview.vars]
ENVIRONMENT = "preview"

[env.production.vars]
ENVIRONMENT = "production"

